export const FETCH_TODOLIST_START = "FETCH_TODOLIST_START"
export const FETCH_TODOLIST_SUCCESS = "FETCH_TODOLIST_SUCCESS"
export const FETCH_TODOLIST_FAILED = "FETCH_TODOLIST_FAILED"
export const FETCH_TODOLIST_LENGTH_SUCCESS = "FETCH_TODOLIST_LENGTH_SUCCESS"

export const ADD_TODO_START = "ADD_TODO_START"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAILED = "ADD_TODO_FAILED"

export const REMOVE_TODO_START = "REMOVE_TODO_START"
export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS"
export const REMOVE_TODO_FAILED = "REMOVE_TODO_FAILED"

export const TOGGLE_TODO_START = "TOGGLE_TODO_START"
export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS"
export const TOGGLE_TODO_FAILED = "TOGGLE_TODO_FAILED"

export const UPDATE_TODO_START = "UPDATE_TODO_START"
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS"
export const UPDATE_TODO_FAILED = "UPDATE_TODO_FAILED"
