export const FETCH_TODOLIST_START = "FETCH_TODOLIST_START"
export const FETCH_TODOLIST_SUCCESS = "FETCH_TODOLIST_SUCCESS"
export const FETCH_TODOLIST_FAILED = "FETCH_TODOLIST_FAILED"

export const ADD_TODO_START = "ADD_TODO_START"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAILED = "ADD_TODO_FAILED"

export const REMOVE_TODO_START = "REMOVE_TODO_START"
export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS"
export const REMOVE_TODO_FAILED = "REMOVE_TODO_FAILED"

export const TOGGLE_TODO_START = "TOGGLE_TODO_START"
export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS"
export const TOGGLE_TODO_FAILED = "TOGGLE_TODO_FAILED"

export const UPDATE_TODO_START = "UPDATE_TODO_START"
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS"
export const UPDATE_TODO_FAILED = "UPDATE_TODO_FAILED"

export const FILTER_TODO_START = "FILTER_TODO_START"
export const FILTER_TODO_SUCCESS = "FILTER_TODO_SUCCESS"
export const FILTER_TODO_FAILED = "FILTER_TODO_FAILED"

export const SEARCH_TODO_START = "SEARCH_TODO_START"
export const SEARCH_TODO_SUCCESS = "SEARCH_TODO_SUCCESS"
export const SEARCH_TODO_FAILED = "SEARCH_TODO_FAILED"

export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const LOGOUT = "LOGOUT"
export const CHECK_TOKEN = "CHECK_TOKEN"

export const CHANGE_GET_TODO_PARAMS = "CHANGE_GET_TODO_PARAMS"
